### ISSUE TITLE
Update release on puppetforge?

### ISSUE THREAD

**Issue by tarioch** [MiamiOH/puppet-httpproxy#8]
It looks like the newer releases are not on puppet forge, is there a reason for that?

**Comment by edestecd** [comment]
Yes, we are waiting on a new release of puppetlabs-apt.
We submitted this pull request, which was merged and should make it into the next release (2.1.2)
https://github.com/puppetlabs/puppetlabs-apt/commit/849d000ff335d460fbb11a4d4ee4a83affff729d

Our new features depend on that.  So if you need it now, you will need to use librarian-puppet and checkout from git both puppet-httpproxy and puppetlabs-apt at master.

We can also open an issue to the apt module, asking for a new release ;)

**Comment by edestecd** [comment]
I have opened a ticket:
https://tickets.puppetlabs.com/browse/MODULES-2596

**Comment by callahm3** [comment]
New version released
